version: '3.8'

services:
  # Backend server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9090:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: vk
      DB_PASSWORD: 1234
      DB_NAME: eduflex
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduflex
      MYSQL_USER: vk
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/eduflexdb.sql:/docker-entrypoint-initdb.d/eduflexdb.sql  # Mount the SQL file for initialization
      - ./init/my.cnf:/etc/mysql/conf.d/my.cnf:ro # Custom configs
    networks:
      - app-network

  # Frontend (React client)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    networks:
      - app-network
    depends_on:
      - server
    volumes:
      - ./client:/app

volumes:
  mysql_data:

networks:
  app-network:
